spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_username}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  devtools:
    restart:
      enabled: true

  output:
    ansi:
      enabled: always

jwt:
  secret: ${JWT_SECRET}
  time:
    access: 3600000      # 1 hour (ms)
    refresh: 2592000000  # 30 days (ms)

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    authentication:
      username: ${SWAGGER_USERNAME}
      password: ${SWAGGER_PW}
      profile-scope:
        - dev

discord:
  web-hook-url: ${DISCORD_WEBHOOK_URL}